import { useState, useRef, MouseEventHandler } from 'react';
import Head from 'next/head';
import Table from '@/components/Table';
import Chart from '@/components/Chart';
import styles from '@/styles/Home.module.css';

const initialState = [
  {
    year: 2018,
    amount: 20,
    group: 'A',
    description: 'Running on-demand all A instances',
  },
  {
    year: 2019,
    amount: 40,
    group: 'B',
    description: 'Running on-demand all B instances',
  },
  {
    year: 2020,
    amount: 39,
    group: 'C',
    description: 'Running on-demand all C instances',
  },
  {
    year: 2021,
    amount: 10,
    group: 'D',
    description: 'Running on-demand all D instances',
  },
  {
    year: 2022,
    amount: 55,
    group: 'E',
    description: 'Running on-demand all E instances',
  },
  {
    year: 2023,
    amount: 70,
    group: 'F',
    description: 'Running on-demand all F instances',
  },
];

const headers = ['Year', 'Amount', 'Group', 'Description'];

export default function Home() {
  const [rows, setRows] = useState(initialState);
  const containerRef = useRef<HTMLDivElement | null>(null);

  const handleScroll: MouseEventHandler<HTMLButtonElement> = (e) => {
    if (containerRef.current) {
      const container = containerRef.current.getBoundingClientRect();
      window.scrollTo({
        top: container.top,
        left: 0,
        behavior: 'smooth',
      });
    }
  };
  return (
    <>
      <Head>
        <title>Syndica</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <header className={styles.header}>
          <img
            className={styles.companyLogo}
            alt='Syndica logo'
            src='/syndica-logo.webp'
          />
        </header>
        <div className={styles.container}>
          <Table rows={rows} headers={headers} />
          <div className={styles.chevron}>
            <button onClick={handleScroll}>
              <img src='/chevron-down.svg' />
            </button>
          </div>
        </div>
        <div className={styles.container} ref={containerRef}>
          <Chart />
        </div>
      </main>
    </>
  );
}
